---
- hosts: db
  become: yes
  gather_facts: 0
  tasks:
    - name: Instal packages
      yum:
        name: "{{ item }}"
        state: present
      #with_items:
      loop:
        - curl
        - finger
        - wget
        - httpd
        - ntp
